[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
anchor_counter = "91EVVU4XLk4kn8ZhrUZUq8vMWh2r8JFvtKa8KiDtK3EU"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/minhbear/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
